version: '3'
services:
 go_db_service:
   image: postgres:14.3
   restart: always
   ports:
     - "7530:5432"
   environment:
     - POSTGRES_USER=edteam
     - POSTGRES_PASSWORD=edteam
     - POSTGRES_DB=godb
   container_name: 'godbedteam'
   volumes:
     - ./postgres-data:/var/lib/postgresql/data